title: "Bima Wicaksana"  # your name or site title
logo: "/images/photo_profile.png?raw=true"  # path to your photo in /images/
description: > 
  Research in international trade, maritime transport, and data analytics. 
  <br><br>
  Master's student in International Trade at KEDGE Business School. 
  <br><br>
  <a href="https://www.linkedin.com/in/YOUR-LINKEDIN/">View My LinkedIn Profile</a> 

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

google_analytics: ""  # leave blank unless you have a Google Analytics ID

github: bimawicaksana  # your GitHub username

# Navigation links shown at the top of the page
navigation:
  - name: "Home"
    link: "index"
  - name: "Projects"
    link: "projects"
  - name: "Research"
    link: "research"

# Theme settings
markdown: kramdown
